#!/usr/bin/env python3
"""배포 빌드에 주입할 publishable Supabase 설정 모듈을 생성한다.

빌드 산출물이 온라인 계정·게스트 ingest를 활성화하도록, `src/mdlogger/remote/
_bundled_config.py`를 소유자 값으로 만든다. 이 모듈은 `.gitignore` 되어 커밋되지
않으며, PyInstaller가 패키지 안에서 발견해 번들한다.

사용(소유자)::

    MDLOGGER_SUPABASE_URL=... MDLOGGER_SUPABASE_ANON_KEY=... \\
        uv run python scripts/generate_build_config.py

또는 ``--url``/``--anon-key`` 인자로 지정.

실패 조건:
- URL 또는 anon key가 비어 있음.
- anon key 자리에 service-role/secret key 또는 role='service_role' JWT.
- URL authority부에 user:pass 자격 증명.

생성 직후 산출 모듈을 재스캔해 service-role key·secret이 없음을 보장한다.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from mdlogger.secret_scan import assert_not_secret, scan_file

_URL_ENV = "MDLOGGER_SUPABASE_URL"
_ANON_KEY_ENV = "MDLOGGER_SUPABASE_ANON_KEY"
_BUNDLED_REL = Path("mdlogger") / "remote" / "_bundled_config.py"

_HEADER = (
    '"""Generated by scripts/generate_build_config.py. Do not edit.\n\n'
    "publishable(anon) Supabase credential(로드맵 8.1 허용).\n"
    "service-role/secret key, password, refresh token은"
    "절대 이 파일에 들어가지 않는다.\n"
    '"""\n'
)


def _default_module_path() -> Path:
    return Path(__file__).resolve().parents[1] / "src" / _BUNDLED_REL


def _render_module(base_url: str, anon_key: str) -> str:
    return (
        _HEADER
        + f"SUPABASE_URL = {base_url!r}\n"
        + f"SUPABASE_ANON_KEY = {anon_key!r}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="publishable Supabase 설정 모듈 생성")
    parser.add_argument(
        "--url", default=os.environ.get(_URL_ENV, "").strip(), help="Supabase base URL"
    )
    parser.add_argument(
        "--anon-key",
        dest="anon_key",
        default=os.environ.get(_ANON_KEY_ENV, "").strip(),
        help="publishable(anon) key",
    )
    parser.add_argument(
        "--dest",
        type=Path,
        default=None,
        help="출력 모듈 경로(기본: src/mdlogger/remote/_bundled_config.py)",
    )
    args = parser.parse_args()
    path = args.dest if args.dest is not None else _default_module_path()

    base_url = args.url.strip()
    anon_key = args.anon_key.strip()
    if not base_url or not anon_key:
        print(
            "오류: MDLOGGER_SUPABASE_URL과 MDLOGGER_SUPABASE_ANON_KEY가 모두 필요합니다.",
            file=sys.stderr,
        )
        return 1

    try:
        assert_not_secret(base_url, anon_key)
    except ValueError as exc:
        print(f"오류: {exc}", file=sys.stderr)
        return 1

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render_module(base_url, anon_key), encoding="utf-8")

    issues = scan_file(path)
    if issues:
        print(f"오류: 생성 모듈에 비밀이 검출됨: {issues}", file=sys.stderr)
        path.unlink(missing_ok=True)
        return 1

    print(f"OK: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
